% Straight up stealing preamble from Eli Holmes 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%START PREAMBLE THAT IS THE SAME FOR ALL EXAMPLES
\documentclass{article}

%Required: You must have these
\usepackage{Sweave}
\usepackage{graphicx}
\usepackage{tabularx}
\usepackage{hyperref}

%Strongly recommended
  %put your figures in one place
\SweaveOpts{prefix.string=figures/, eps=FALSE} 
%you'll want these for pretty captioning
\usepackage[small]{caption}

\setkeys{Gin}{width=0.8\textwidth}  %make the figs 50 perc textwidth
\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{0pt}
\setlength{\belowcaptionskip}{10pt}
% manual for caption  http://www.dd.chalmers.se/latex/Docs/PDF/caption.pdf

%Optional: I like to muck with my margins and spacing in ways that LaTeX frowns on
%Here's how to do that
 \topmargin -1.5cm        
 \oddsidemargin -0.04cm   
 \evensidemargin -0.04cm  % same as oddsidemargin but for left-hand pages
 \textwidth 16.59cm
 \textheight 21.94cm 
 %\pagestyle{empty}       % Uncomment if don't want page numbers
 \parskip 7.2pt           % sets spacing between paragraphs
 %\renewcommand{\baselinestretch}{1.5} 	% Uncomment for 1.5 spacing between lines
\parindent 0pt		  % sets leading space for paragraphs
\usepackage{setspace}
%\doublespacing

%Optional: I like fancy headers
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhead[LO]{How do climate change experiments actually change climate}
\fancyhead[RO]{2016}
 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%END PREAMBLE THAT IS THE SAME FOR ALL EXAMPLES

%Start of the document
\begin{document}
\SweaveOpts{concordance=FALSE}
% \SweaveOpts{concordance=TRUE}
% \bibliographystyle{/Users/Lizzie/Documents/EndnoteRelated/Bibtex/styles/nature.bst}
\title{How do climate change experiments actually change climate?} % Paper 1/Large group paper from Reconciling Experimental and Observational Approaches for Climate Change Impacts
\author{A. K. Ettinger,I. Chuine, B. Cook, J. Dukes, A. Ellison, M. Johnston, A.M. Panetta,\\ C. Rollinson, Y. Vitasse, E. Wolkovich}
%\date{\today}
\maketitle  %put the fancy title on
%\tableofcontents      %add a table of contents
%\clearpage
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section {Aim}

The aim is to write a Concept/Synthesis Paper about maximizing benefits of field-based climate change experiments by improved understanding of how climate is altered by these experiments. Experiments need to report what climate variables are modified by their experiment and how. %yann: perhaps also to determine which methods of warming alter the least other climatic variables or to define the most appropriate method regarding the focus of the study (phenology, growth, survival etc)?%annmarie: Somewhere in this paper,  we should discuss that is important that “how” climate variables are modified relative to the predicted change under various emission scenarios is important.  Thus, the “how” should be not only the direction and magnitude of the variable change but also the extent to which the change mirrors change projected for the region in which the experiment took place)
This is particularly valuable for improving our understanding of biological impacts of climate change.

build up a discussion of studies that report only mean shifts in temperature in the intro. 

\section {Introduction}

\par Experimental in situ climate manipulations offer several advantages to understanding biological impacts of climate change: (controlled, relative speed- i.e. multiple manipulations can be conducted simultaneously, can hit higher temps such as those forecasted, can do them in places where other data collection is hard, are less artificial than ex situ controlled experiments such as chambers%annmarie: what kind of data collection is hard?
\par These advantages come at a cost, however. Experimental in situ climate manipulations are logistically challenging, expensive, and more important: other climatic variables than the target ones are affected with possible interactions (often overlooked), And it is dfficult to design replicated experiments that actually do the interactions well, and even moderately realistically.
\par \underline{Problem:} People often want to extrapolate the results of warming experiments to real life to understand (and forecast) biological impacts of climate change. Even in cases when this is not the explicit goal, it would be incredibly useful to be able to apply knowledge gained from these experiments to improve our understanding and forecasting of how anthropogenic warming will affect species' performance (growth, survival) and distributions, as well as on differences in responses among provenances/genotypes/species. However, our ability to make this application is limited because a detailed assessment of exactly how experimental warming treatments alter climate, and the extent to which these manipulations accurately model the real world,
is lacking. Furthermore, especially given the high number of warming methods applied, rising another question: are they comparable?% when you say “the real world” do you mean contemporary climate change or present-day relationships between temperature, moisture, etc? 
%%%%Lizzie: I think eventually we want the tone here to acknowledge that not every experiment sets out to extrapolate to climate change, but some do -- and that really is a goal we should have. This could eventually give us an elegant way to focus in on only a couple experimental designs. 
\section {Experimental climate change vs. real climate:
how do they compare?}%Again, I find the “real climate” phrase confusing.   Also, a different subject heading may be appropriate given the points below.  Points 3.1-3.4 seem to highlight complicating factors rather than clear comparisons between experimental warming effects and observed effects due to contemporary climate change.  
\subsection {Infrastructure}
The experimental structures themselves alter temperature and other important biotic and abiotic variables (see note below), in ways that are not generally examined or reported in experimental warming studies. Compare sham and ambient data on temperature (mixed effects models). we should also make explicit what a sham is and how a control plot should be%
\begin{itemize}
\item Soil temperature is LOWER in the shams, compared with the ambient air (Figure 1). Define exp methods included in this analyses, and other details.
\item Air temperature is HIGHER in the shams, compared with the ambient air (Figure 1).
\item The pattern was consistent for min and max air and soil temperatures, as well (Figure 2).
\item From anne-marie: It seems as though it may be interesting (and important) to focus on other variables that shams may affect than temperature, as the net effect of the sham plus the intended temperature treatment is often what is measured/reported. We should think about discussing the facts that infrastructure may shade the plots and intercept precipitation.  Thus, if covariates of soil moisture and solar radiation are not measured/considered, there could be erroneous conclusions about cause and effect.  Perhaps even more importantly, there have been a number of good studies now that show that there are important interactions between warming and herbivory.  Thus, if shams affect access of herbivores to the plots (like open-top chambers may do), they may give results that are not realistic.  (This discussion should likely go in the biotic interactions section, but should be mentioned here in the infrastructure section.  I am happy to provide some good references.)
I am not convinced by section 3.1 (as it stands now) hat this is important, as long as all of the temperature, moisture, humidity data from the treatment and control plots are reported.  Why go through all the extra cost (and space)?  If we are to make this argument, I think it needs more supporting evidence/ discussion in section 3.1 (please see my notes on initial ideas on how to do so)
\end{itemize}
\subsection {Space}
There is spatial variation in experimental warming effects, such that extrapolation of experimental warming to forecast climate change impacts may not be a straightforward space-for-time subsitution. Presumably there will also be spatial variation in climate change effects.  Accurate extrapolation may therefore depend on the extent to which experiments encompass a representative amount of existing natural variation (gradients in slope, aspect, etc) present at the scale at which the extrapolation is being made.% from aaron: And most space-for-time substitutions turn out to be inaccurate. I think because we make assumptions about state of assemblages and temporal stationarity that are unrealistic.
\begin{itemize}
\item Analysis of plot vs. block level variation vs. treatment effects. Lizzie is working on this.
\item Documented variation in warming within plots (i.e. edge effects)? (This is known for open-top chambers)
\end{itemize}
\subsection {Time}
In addition, there is often temporal variation in experimental warming, and this variation may be divergent from real (i.e. non-experimental) temperature patterns so it should carefully be considered in extrapolating experimental warming to future climate change impacts. Add details and examples of why this occurs, since warming experiments are tied to ambient conditions. 
\begin{itemize}
\item Seasonal variations in experimental warming effects (plots over time; Christy is working on this?).
\item Daily variations in experimental warming effects (Tmin vs Tmax). This is often neglected (common to report only the daily mean temperature that may hide huge variations in min and max) and recently there are several papers showing the importance of diurnal over nocturnal temperature on phenology.
\item Compare these seasonal and daily variations to observational data (i.e. plot seasonal and daily variations for warmest vs coldest years)
\item Treatments are not applied consistently over the year- IR heaters can't
apply consistent warming throughout the year, and some warming experiments turn off warming during some seasons (e.g. Clark et al, this is very common in the heating cable exp, like the ones in Austria, Norway, it is likely that this would yield different effects than if heating were turned on during winter (because then you change soil nutrient mineralization which might be important in winter and so change nutrient availability and moisture for the growing season). 
\item Include a discussion that 3-5 year studies may not capture ultimate, long-term responses that may actually be in the opposite direction to short-term responses.  Site recent Global Change Biology paper by Harte et al.  Ideally, we want to run studies long enough to capture population-level responses to warming.
\end{itemize}
\section {Secondary effects of warming}
Temperature interacts with many other climatic and nonclimatic factors to alter the abiotic environment. It is important that experimentally induced changes in other variables are realistic; for example, that experimental treatment does not increase moisture an an area projected to get much drier). Understanding the effect of an experimental treatment on the suite of interrelated variables becomes particularly  important when one is trying to determine mechanistic explanations for observed responses to warming.
\begin{itemize}
\item Effects of experimental warming on air humidity (use Isabelle's data?). This affects VPD with potential impact for stomata closure (paper out on this response (sapflow, vpd) from Pam Templer's group using Harvard Forest ant warming chambers effects on oak trees)
\item Change in biotic interactions, I mean if warming increase the abundance and composition of species it might change competition for resources...
\item 
\end{itemize}
\section {Biological Implications}
\par We have highlighted a suite of factors that complicate simple interpretation of warming experiments. We argue that these largely unintended alterations are important for scientists to fully understand and report in their research because they are likely to have biological implications. 
\par Examples:
\begin{itemize}
\item Plant phenology: likely to be altered in opposing ways by
the increased air temperatures and decrease soil moisture/temperature, cite Wolkavich et al's earlier work finding discrepency between observation and experimental phenology responses to warming. (Aaron: plants also respond to variability, perhaps more than mean, as we saw in W Mass this year with fruit tree flowering)
\item Soil respiration or other microbe studies? (tight link between microbial activity and plant growth under warming. net mineralization should be accounted for)
\item Plant growth- photosynthesis and transpiration are likely to be altered in opposing ways by the increased air temperatures and decrease soil moisture/temperature %Lizzie: I think you could find simple references in Larcher or another basic plant physiology book (Terry Chapin's?) to small temperature changes having a big effect. aforementioned paper by Templer group (Ecosphere 2016) may be a useful example. Paper here: http://harvardforest.fas.harvard.edu/sites/harvardforest.fas.harvard.edu/files/ellison-pubs/2016/Juice_etal_2016_Ecosphere.pdf
\item change in biotic interactions (see previous comment): both plant-plant and microbes/fungi-plants
\item intraspecific variation? All plants, ants, microbes, etc. of a single species not equivalently responsive. 

\item genetic component? GXE interactions?
\item herbivory
\end{itemize}

\section {Recommendations for future climate change experiments}
 \par The warming effects we describe are not meant to be criticisms or to imply that experimental warming studies are not worthwhile. On the contrary, we believe that climate change experiments provide invaluable information about biological responses to warming. We also believe that we need to more fully explore the ways in which these warming experiments are altering climate, as it is clearly not simply shifting the mean. Here we describe a few recommendations to improve implementation, interpretation, and communication of future climate change experiments.
 \begin{itemize}

\item Include sham and ambient controls, and collect, use, and report data collectedwithin them. (carefully define what is a sham in the intro)
 \item Carefully consider and report the timing of warming treatment applied,including exact start and end dates within and across years.
 \item Collect climate data at least twice daily, and ideally hourly; report these data, in particular, variations in daytime and nighttime and season variations in climate variables. can use time-series modeling, not just monthly (or even daily) means. Get the ACF and PACF
\item Report the number and cause of missing data points for climate, especially
 those collected in warming treatments. For example, are data missing
 because the heaters went out, or because rodents at the sensors?
\item Consider implementing and following community standards for reporting
 climate data (and phenology -Chuine et al. 2017)
\item Construct regression designs to examine possible nonlinear responses to
 warming
\item Publish data with good, useful metadata!
\item Publish data with good, useful metadata! Recommend archives?
\item Warming experiments should run for several seasons to account for the interannual variations that may interact with the warming treatment itself (especially when looking at non linear processes such as phenology)
\item Prior to experimental setup, consult climate change projections for the study region.  Pick a warming/precipitation treatment method that most accurately mimics anticipated changes. Or at the minimum, report how your study compares to projected changes.
\item Run experiment long enough to capture more than transient responses.  
 \end{itemize}
%Notes from Aaron, who doesn't think that pooling the plots makes sense. (I should explain that I used mixed effects models with random effect of site to account for this):There are some big differences in exps that are obscured by pooling in these plots. Because of that, pooling them doesn't make sense to me.Farnsworth is soil-warming cables only Clarkduke & Clarkharvard are soil warming cables + air heating, but air heating is turned off in winter at Harvard (not sure about Duke) while cables (I think) were left on.
% ellison and marchin are air warming only, run all year.below, it seems as though we should mention ( in this section and perhaps even in the intro) that these recommendations stem from an attempt to gather and analyze data from many warming experiments.  We could make some sort of statement about how important it is, when trying to understand implications of a global challenge as large as climate change, that we design, run, and report experiments in such a way that we may eventually give rise to a global dataset.
\end{document}
