\documentclass{article}

\begin{document}
\SweaveOpts{concordance=FALSE}
\section* {Tables}
\begin{table}
  \caption{{\bf Sites included in the C3E database}. Experimental sites
    correspond to map (Figure 1, main text). We give the study ID, location, source, years of data included, and warming type used in the study. Note that some sites may have
    multiple sources; howeverm we list only one.}
\begin{footnotesize} 
   \begin{tabular}{| p{1cm} | p{4.5cm} | p{2.5cm} | p{1cm} | p{2cm} |}
    \hline
  study id & location & source & data years & warming type \\ \hline
    exp01 & Waltham, MA, USA & hoeppner2012 & 2010-2014 & infrared\\ \hline
    exp02 & Montpelier, France & morin2010 & 2002-2005 & infrared\\ \hline
    exp03 & Duke Forest, NC, USA & clark2014a & 2009-2012 & forced air and soil warming\\ \hline
    exp04 & Harvard Forest, MA, USA & clark2014a & 2000-2002 & forced air and soil warming\\ \hline
    exp05 & Jasper Ridge Biological Preserve, CA, USA &cleland2007 & 2009-2012 & infrared\\ \hline
    exp06 & Rocky Mountain Biological Lab, CO, USA & dunne2003 & 1995-1998 & infrared\\ \hline
    exp07 & Harvard Forest, MA, USA & pelini & 2009-2010 & forced air \\ \hline
    exp08 & Harvard Forest, MA, USA & farnsworth1995 & 1993 & soil warming \\ \hline
    exp09 & Stone Valley Forest, PA, USA & rollinson2012 & 2009-2010 & infrared \\ \hline
    exp10 & Duke Forest, NC, USA & marchin2015 & 2010-2012 & forced air \\ \hline
    exp11 & Rocky Mountain Biological Lab, CO, USA & price1998 & 1991-1994 & infrared\\ \hline
    exp12 & Kessler Farm Field Laboratory,OK, USA & sherry2007 & 2003 & infrared\\ \hline
    \end{tabular}    
\end{footnotesize} 
    \end{table}

\end{document}